# Week 13 Review Assignmnet

For the questions below, we're going to refer exclusively to an HHCAPS survey data set that is available in `/data/hhcaps.csv`.  Use whatever commands you want to calculate the information required to get to the answer.  Then, enter your answer in the answers cell as usual.

**NOTE: Enter your answers as string values (inside quotation marks "") even if the answer is actually numeric.**

---
---

In [1]:
%matplotlib inline
import pandas as pd

hhcaps = pd.read_csv('/data/hhcaps.csv')

## #01 - 

How many columns does this file contain?

In [2]:
# Write some code to figure it out
column_count = len(hhcaps.columns)

In [3]:
column_count

39

In [4]:
from numpy import int64

In [5]:
column_count = int64(column_count)

In [6]:
answers={}
answers['39'] = column_count

## #02 - 

How many different values for State are there in this file?

In [7]:
 state_count = hhcaps.groupby("State").count()

In [8]:
state_count

,CMS Certification Number (CCN)*,Provider Name,Address,City,Zip,Phone,Type of Ownership,Offers Nursing Care Services,Offers Physical Therapy Services,Offers Occupational Therapy Services,...,Star Rating for how patients rated overall care from agency,Footnote for Star Rating for overall care from agency,Percent of patients who gave their home health agency a rating of 9 or 10 on a scale from 0 (lowest) to 10 (highest),Footnote for percent of patients who gave their home health agency a rating of 9 or 10 on a scale from 0 (lowest) to 10 (highest),"Percent of patients who reported YES, they would definitely recommend the home health agency to friends and family","Footnote for percent of patients who reported YES, they would definitely recommend the home health agency to friends and family",Number of completed Surveys,Footnote for number of completed surveys,Response rate,Footnote for response rate
State,,,,,,,,,,,,,,,,,,,,,
AK,14,14,14,14,14,14,14,14,14,14,...,6,13,14,13,14,13,14,13,14,13
AL,152,152,152,152,152,152,152,152,152,152,...,130,62,152,62,152,62,152,62,152,62
AR,172,172,172,172,172,172,172,172,172,172,...,78,112,172,112,172,112,172,112,172,112
AZ,169,169,169,169,169,169,169,169,169,169,...,83,111,169,111,169,111,169,111,169,111
CA,1319,1319,1319,1319,1319,1319,1319,1319,1319,1319,...,488,1069,1319,1069,1319,1069,1319,1069,1319,1069
CO,187,187,187,187,187,187,187,187,187,187,...,96,130,187,130,187,130,187,130,187,130
CT,91,91,91,91,91,91,91,91,91,91,...,69,37,91,37,91,37,91,37,91,37
DC,28,28,28,28,28,28,28,28,28,28,...,6,24,28,24,28,24,28,24,28,24
DE,26,26,26,26,26,26,26,26,26,26,...,13,16,26,16,26,16,26,16,26,16
FL,1069,1069,1069,1069,1069,1069,1069,1069,1069,1069,...,482,755,1069,755,1069,755,1069,755,1069,755
GA,106,106,106,106,106,106,106,106,106,106,...,97,20,106,20,106,20,106,20,106,20
GU,4,4,4,4,4,4,4,4,4,4,...,0,4,4,4,4,4,4,4,4,4
HI,16,16,16,16,16,16,16,16,16,16,...,11,10,16,10,16,10,16,10,16,10
IA,163,163,163,163,163,163,163,163,163,163,...,98,122,163,122,163,122,163,122,163,122
ID,45,45,45,45,45,45,45,45,45,45,...,36,25,45,25,45,25,45,25,45,25
IL,735,735,735,735,735,735,735,735,735,735,...,289,593,735,593,735,593,735,593,735,593
IN,229,229,229,229,229,229,229,229,229,229,...,133,147,229,147,229,147,229,147,229,147
KS,117,117,117,117,117,117,117,117,117,117,...,66,74,117,74,117,74,117,74,117,74
KY,104,104,104,104,104,104,104,104,104,104,...,97,25,104,25,104,25,104,25,104,25
LA,195,195,195,195,195,195,195,195,195,195,...,164,75,195,75,195,75,195,75,195,75
MA,261,261,261,261,261,261,261,261,261,261,...,104,180,261,180,261,180,261,180,261,180
MD,53,53,53,53,53,53,53,53,53,53,...,46,10,53,10,53,10,53,10,53,10
ME,24,24,24,24,24,24,24,24,24,24,...,20,10,24,10,24,10,24,10,24,10
MI,597,597,597,597,597,597,597,597,597,597,...,215,476,597,476,597,476,597,476,597,476
MN,197,197,197,197,197,197,197,197,197,197,...,101,151,197,151,197,151,197,151,197,151
MO,169,169,169,169,169,169,169,169,169,169,...,113,96,169,96,169,96,169,96,169,96
MP,2,2,2,2,2,2,2,2,2,2,...,0,2,2,2,2,2,2,2,2,2
MS,48,48,48,48,48,48,48,48,48,48,...,44,7,48,7,48,7,48,7,48,7
MT,27,27,27,27,27,27,27,27,27,27,...,18,20,27,20,27,20,27,20,27,20
NC,174,174,174,174,174,174,174,174,174,174,...,152,49,174,49,174,49,174,49,174,49
ND,18,18,18,18,18,18,18,18,18,18,...,12,10,18,10,18,10,18,10,18,10
NE,75,75,75,75,75,75,75,75,75,75,...,36,54,75,54,75,54,75,54,75,54
NH,31,31,31,31,31,31,31,31,31,31,...,22,13,31,13,31,13,31,13,31,13
NJ,47,47,47,47,47,47,47,47,47,47,...,42,9,47,9,47,9,47,9,47,9
NM,77,77,77,77,77,77,77,77,77,77,...,56,50,77,50,77,50,77,50,77,50
NV,143,143,143,143,143,143,143,143,143,143,...,71,119,143,119,143,119,143,119,143,119
NY,141,141,141,141,141,141,141,141,141,141,...,103,54,141,54,141,54,141,54,141,54
OH,781,781,781,781,781,781,781,781,781,781,...,288,604,781,604,781,604,781,604,781,604
OK,256,256,256,256,256,256,256,256,256,256,...,171,174,256,174,256,174,256,174,256,174
OR,57,57,57,57,57,57,57,57,57,57,...,44,23,57,23,57,23,57,23,57,23
PA,425,425,425,425,425,425,425,425,425,425,...,209,265,425,265,425,265,425,265,425,265
PR,45,45,45,45,45,45,45,45,45,45,...,26,28,45,28,45,28,45,28,45,28
RI,27,27,27,27,27,27,27,27,27,27,...,19,10,27,10,27,10,27,10,27,10
SC,70,70,70,70,70,70,70,70,70,70,...,60,23,70,23,70,23,70,23,70,23
SD,33,33,33,33,33,33,33,33,33,33,...,12,26,33,26,33,26,33,26,33,26
TN,140,140,140,140,140,140,140,140,140,140,...,118,45,140,45,140,45,140,45,140,45
TX,2518,2518,2518,2518,2518,2518,2518,2518,2518,2518,...,807,2145,2518,2145,2518,2145,2518,2145,2518,2145
UT,98,98,98,98,98,98,98,98,98,98,...,53,70,98,70,98,70,98,70,98,70
VA,244,244,244,244,244,244,244,244,244,244,...,149,142,244,142,244,142,244,142,244,142
VI,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
VT,11,11,11,11,11,11,11,11,11,11,...,11,1,11,1,11,1,11,1,11,1
WA,63,63,63,63,63,63,63,63,63,63,...,56,16,63,16,63,16,63,16,63,16
WI,119,119,119,119,119,119,119,119,119,119,...,69,76,119,76,119,76,119,76,119,76
WV,61,61,61,61,61,61,61,61,61,61,...,51,25,61,25,61,25,61,25,61,25
WY,26,26,26,26,26,26,26,26,26,26,...,12,21,26,21,26,21,26,21,26,21

In [9]:
answers['40.2'] = state_count

## #03 - 

Which of those State values has the highest frequency of occurence?

In [10]:
freq = hhcaps['State'].mode()

In [11]:
freq

0    TX
dtype: object

In [12]:
hhcaps['State'].value_counts().idxmax()

'TX'

In [13]:
answers['40.3'] = TX

NameError: name 'TX' is not defined

## #04 - 

Which of those State values has the best average performance on the `Star Rating for health team communicated well with them` score?

In [ ]:
average = hhcaps.mean(axis='index')

In [ ]:
average

In [ ]:
answers['40.4'] = average

## #05 - 

What was the average score on `Star Rating for how patients rated overall care from agency` for providers listed as having a `Type of Ownership` of `Hospital Based Program`

**NOTE: Enter your answer with two decimal precision: 0.00**

In [ ]:
data = hhcaps['Type of Owernship']=='Hospital Based Program'
average_score = round(hhcaps[data]["Star Rating for how patients rated overall care from agency"].mean(),2)

In [ ]:
average_score

In [ ]:
answers['40.5'] = average_score

---

Checking Your Work
---

After completing your work above and running each cell, you can check your answers by running the code below. 

The easiest way to do this is to use the `Kernel` -> `Restart Kernel and Run All Cells` menu option. This option restarts Python and runs every cell from top to bottom until it encounters an exception of some kind.  It will stop after running the cell below and outputing a summary of how many answers you have correct or incorrect.

In [ ]:
import getpass
import boto3
import json

test = {
    "user": getpass.getuser(),
    "week": "week13",
    "answers": answers
}

client = boto3.client('lambda')

response = client.invoke(
    FunctionName="hds5210",
    InvocationType="RequestResponse",
    Payload=json.dumps(test))

result = json.loads(response['Payload'].read().decode('utf-8'))
# print(result)

try:
    print('{0:>5}{1:>20}{2:>10}'.format('Q#','Yours','Correct?'))
    for row in result.get('results'):
        print('{0:>5}{1:>20}{2:>10}'.format(str(row[0]),str(row[1]),str(row[2])))
except:
    print(result)

---

## Check your work above

If you didn't get them all correct, take a few minutes to think through those that aren't correct.


## Submitting Your Work

Submit your work as usual.